/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and valkey-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscachecssapcomv1alpha1 "github.com/nejec/valkey-operator/api/v1alpha1"
	versioned "github.com/nejec/valkey-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nejec/valkey-operator/pkg/client/informers/externalversions/internalinterfaces"
	cachecssapcomv1alpha1 "github.com/nejec/valkey-operator/pkg/client/listers/cache.cs.sap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ValkeyInformer provides access to a shared informer and lister for
// Valkey.
type ValkeyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cachecssapcomv1alpha1.ValkeyLister
}

type valkeyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewValkeyInformer constructs a new informer for Valkey type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewValkeyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredValkeyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredValkeyInformer constructs a new informer for Valkey type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredValkeyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().Valkey(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().Valkey(namespace).Watch(context.TODO(), options)
			},
		},
		&apiscachecssapcomv1alpha1.Valkey{},
		resyncPeriod,
		indexers,
	)
}

func (f *valkeyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredValkeyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *valkeyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscachecssapcomv1alpha1.Valkey{}, f.defaultInformer)
}

func (f *valkeyInformer) Lister() cachecssapcomv1alpha1.ValkeyLister {
	return cachecssapcomv1alpha1.NewValkeyLister(f.Informer().GetIndexer())
}
