/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and valkey-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	cachecssapcomv1alpha1 "github.com/nejec/valkey-operator/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ValkeyLister helps list Valkey.
// All objects returned here must be treated as read-only.
type ValkeyLister interface {
	// List lists all Valkey in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cachecssapcomv1alpha1.Valkey, err error)
	// Valkey returns an object that can list and get Valkey.
	Valkey(namespace string) ValkeyNamespaceLister
	ValkeyListerExpansion
}

// valkeyLister implements the ValkeyLister interface.
type valkeyLister struct {
	listers.ResourceIndexer[*cachecssapcomv1alpha1.Valkey]
}

// NewValkeyLister returns a new ValkeyLister.
func NewValkeyLister(indexer cache.Indexer) ValkeyLister {
	return &valkeyLister{listers.New[*cachecssapcomv1alpha1.Valkey](indexer, cachecssapcomv1alpha1.Resource("valkey"))}
}

// Valkey returns an object that can list and get Valkey.
func (s *valkeyLister) Valkey(namespace string) ValkeyNamespaceLister {
	return valkeyNamespaceLister{listers.NewNamespaced[*cachecssapcomv1alpha1.Valkey](s.ResourceIndexer, namespace)}
}

// ValkeyNamespaceLister helps list and get Valkey.
// All objects returned here must be treated as read-only.
type ValkeyNamespaceLister interface {
	// List lists all Valkey in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*cachecssapcomv1alpha1.Valkey, err error)
	// Get retrieves the Valkey from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*cachecssapcomv1alpha1.Valkey, error)
	ValkeyNamespaceListerExpansion
}

// valkeyNamespaceLister implements the ValkeyNamespaceLister
// interface.
type valkeyNamespaceLister struct {
	listers.ResourceIndexer[*cachecssapcomv1alpha1.Valkey]
}
