/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and valkey-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nejec/valkey-operator/api/v1alpha1"
	cachecssapcomv1alpha1 "github.com/nejec/valkey-operator/pkg/client/clientset/versioned/typed/cache.cs.sap.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeValkey implements ValkeyInterface
type fakeValkey struct {
	*gentype.FakeClientWithList[*v1alpha1.Valkey, *v1alpha1.ValkeyList]
	Fake *FakeCacheV1alpha1
}

func newFakeValkey(fake *FakeCacheV1alpha1, namespace string) cachecssapcomv1alpha1.ValkeyInterface {
	return &fakeValkey{
		gentype.NewFakeClientWithList[*v1alpha1.Valkey, *v1alpha1.ValkeyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("valkey"),
			v1alpha1.SchemeGroupVersion.WithKind("Valkey"),
			func() *v1alpha1.Valkey { return &v1alpha1.Valkey{} },
			func() *v1alpha1.ValkeyList { return &v1alpha1.ValkeyList{} },
			func(dst, src *v1alpha1.ValkeyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ValkeyList) []*v1alpha1.Valkey { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ValkeyList, items []*v1alpha1.Valkey) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
